language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6-dev" # 3.6 development branch
# command to install dependencies
install: "pip install -r requirements.pip -r requirements-test.pip"
# command to run tests
script: py.test -vv --junit-xml=tests-result.xml
